// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "../behaviac_types.h"

// -------------------
// Customized enums
// -------------------

BEHAVIAC_BEGIN_ENUM_EX(TaskType, TaskType)
{
	BEHAVIAC_ENUMCLASS_DISPLAY_INFO_EX(L"TaskType", L"");

	BEHAVIAC_ENUM_ITEM_EX(SetTargetType, "SetTargetType");
	BEHAVIAC_ENUM_ITEM_EX(TurnBack, "TurnBack");
	BEHAVIAC_ENUM_ITEM_EX(MoveTo, "MoveTo");
}
BEHAVIAC_END_ENUM_EX()

