// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#include "behaviac/common/meta.h"
#include "behaviac/common/member.h"
#include "behaviac_agent_meta.h"

namespace behaviac
{
	class CMethod_behaviac_Agent_VectorAdd : public CAgentMethodVoidBase
	{
		IInstanceMember* _param0;
		IInstanceMember* _param1;

	public: 
		CMethod_behaviac_Agent_VectorAdd() : _param0(0) , _param1(0) 
		{
		}

		CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd &rhs) : CAgentMethodVoidBase(rhs) , _param0(0) , _param1(0) 
		{
		}

		~CMethod_behaviac_Agent_VectorAdd()
		{
			BEHAVIAC_DELETE _param0;
			BEHAVIAC_DELETE _param1;
		}

		virtual IInstanceMember* clone()
		{
			return BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd(*this);
		}

		virtual void load(const char* instance, behaviac::vector<behaviac::string>& paramStrs)
		{
			BEHAVIAC_ASSERT(paramStrs.size() == 2);

			behaviac::StringUtils::StringCopySafe(kInstanceNameMax, _instance, instance);
			_param0 = AgentMeta::TParseProperty<IList >(paramStrs[0].c_str());
			_param1 = AgentMeta::TParseProperty<System::Object >(paramStrs[1].c_str());
		}

		virtual void run(Agent* self)
		{
			BEHAVIAC_ASSERT(_param0 != NULL);
			BEHAVIAC_ASSERT(_param1 != NULL);

			IList& pValue_param0 = *(IList*)_param0->GetValue(self, behaviac::Meta::IsVector<IList >::Result, behaviac::GetClassTypeNumberId<IList >());
			System::Object& pValue_param1 = *(System::Object*)_param1->GetValue(self, behaviac::Meta::IsVector<System::Object >::Result, behaviac::GetClassTypeNumberId<System::Object >());
			behaviac::Agent::VectorAdd(pValue_param0, pValue_param1);
		}
	};

	class CMethod_behaviac_Agent_VectorClear : public CAgentMethodVoidBase
	{
		IInstanceMember* _param0;

	public: 
		CMethod_behaviac_Agent_VectorClear() : _param0(0) 
		{
		}

		CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear &rhs) : CAgentMethodVoidBase(rhs) , _param0(0) 
		{
		}

		~CMethod_behaviac_Agent_VectorClear()
		{
			BEHAVIAC_DELETE _param0;
		}

		virtual IInstanceMember* clone()
		{
			return BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear(*this);
		}

		virtual void load(const char* instance, behaviac::vector<behaviac::string>& paramStrs)
		{
			BEHAVIAC_ASSERT(paramStrs.size() == 1);

			behaviac::StringUtils::StringCopySafe(kInstanceNameMax, _instance, instance);
			_param0 = AgentMeta::TParseProperty<IList >(paramStrs[0].c_str());
		}

		virtual void run(Agent* self)
		{
			BEHAVIAC_ASSERT(_param0 != NULL);

			IList& pValue_param0 = *(IList*)_param0->GetValue(self, behaviac::Meta::IsVector<IList >::Result, behaviac::GetClassTypeNumberId<IList >());
			behaviac::Agent::VectorClear(pValue_param0);
		}
	};

	class CMethod_behaviac_Agent_VectorContains : public CAgentMethodBase<bool>
	{
		IInstanceMember* _param0;
		IInstanceMember* _param1;

	public: 
		CMethod_behaviac_Agent_VectorContains() : _param0(0) , _param1(0) 
		{
		}

		CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains &rhs) : CAgentMethodBase<bool>(rhs) , _param0(0) , _param1(0) 
		{
		}

		~CMethod_behaviac_Agent_VectorContains()
		{
			BEHAVIAC_DELETE _param0;
			BEHAVIAC_DELETE _param1;
		}

		virtual IInstanceMember* clone()
		{
			return BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains(*this);
		}

		virtual void load(const char* instance, behaviac::vector<behaviac::string>& paramStrs)
		{
			BEHAVIAC_ASSERT(paramStrs.size() == 2);

			behaviac::StringUtils::StringCopySafe(kInstanceNameMax, _instance, instance);
			_param0 = AgentMeta::TParseProperty<IList >(paramStrs[0].c_str());
			_param1 = AgentMeta::TParseProperty<System::Object >(paramStrs[1].c_str());
		}

		virtual void run(Agent* self)
		{
			BEHAVIAC_ASSERT(_param0 != NULL);
			BEHAVIAC_ASSERT(_param1 != NULL);

			IList& pValue_param0 = *(IList*)_param0->GetValue(self, behaviac::Meta::IsVector<IList >::Result, behaviac::GetClassTypeNumberId<IList >());
			System::Object& pValue_param1 = *(System::Object*)_param1->GetValue(self, behaviac::Meta::IsVector<System::Object >::Result, behaviac::GetClassTypeNumberId<System::Object >());
			_returnValue->value = behaviac::Agent::VectorContains(pValue_param0, pValue_param1);
		}
	};

	class CMethod_behaviac_Agent_VectorLength : public CAgentMethodBase<int>
	{
		IInstanceMember* _param0;

	public: 
		CMethod_behaviac_Agent_VectorLength() : _param0(0) 
		{
		}

		CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength &rhs) : CAgentMethodBase<int>(rhs) , _param0(0) 
		{
		}

		~CMethod_behaviac_Agent_VectorLength()
		{
			BEHAVIAC_DELETE _param0;
		}

		virtual IInstanceMember* clone()
		{
			return BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength(*this);
		}

		virtual void load(const char* instance, behaviac::vector<behaviac::string>& paramStrs)
		{
			BEHAVIAC_ASSERT(paramStrs.size() == 1);

			behaviac::StringUtils::StringCopySafe(kInstanceNameMax, _instance, instance);
			_param0 = AgentMeta::TParseProperty<IList >(paramStrs[0].c_str());
		}

		virtual void run(Agent* self)
		{
			BEHAVIAC_ASSERT(_param0 != NULL);

			IList& pValue_param0 = *(IList*)_param0->GetValue(self, behaviac::Meta::IsVector<IList >::Result, behaviac::GetClassTypeNumberId<IList >());
			_returnValue->value = behaviac::Agent::VectorLength(pValue_param0);
		}
	};

	class CMethod_behaviac_Agent_VectorRemove : public CAgentMethodVoidBase
	{
		IInstanceMember* _param0;
		IInstanceMember* _param1;

	public: 
		CMethod_behaviac_Agent_VectorRemove() : _param0(0) , _param1(0) 
		{
		}

		CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove &rhs) : CAgentMethodVoidBase(rhs) , _param0(0) , _param1(0) 
		{
		}

		~CMethod_behaviac_Agent_VectorRemove()
		{
			BEHAVIAC_DELETE _param0;
			BEHAVIAC_DELETE _param1;
		}

		virtual IInstanceMember* clone()
		{
			return BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove(*this);
		}

		virtual void load(const char* instance, behaviac::vector<behaviac::string>& paramStrs)
		{
			BEHAVIAC_ASSERT(paramStrs.size() == 2);

			behaviac::StringUtils::StringCopySafe(kInstanceNameMax, _instance, instance);
			_param0 = AgentMeta::TParseProperty<IList >(paramStrs[0].c_str());
			_param1 = AgentMeta::TParseProperty<System::Object >(paramStrs[1].c_str());
		}

		virtual void run(Agent* self)
		{
			BEHAVIAC_ASSERT(_param0 != NULL);
			BEHAVIAC_ASSERT(_param1 != NULL);

			IList& pValue_param0 = *(IList*)_param0->GetValue(self, behaviac::Meta::IsVector<IList >::Result, behaviac::GetClassTypeNumberId<IList >());
			System::Object& pValue_param1 = *(System::Object*)_param1->GetValue(self, behaviac::Meta::IsVector<System::Object >::Result, behaviac::GetClassTypeNumberId<System::Object >());
			behaviac::Agent::VectorRemove(pValue_param0, pValue_param1);
		}
	};

	class BehaviorLoaderImplement : BehaviorLoader
	{
	public:
		BehaviorLoaderImplement()
		{
			AgentMeta::SetBehaviorLoader(this);
		}

		virtual ~BehaviorLoaderImplement()
		{
		}

		virtual bool load()
		{
			AgentMeta::SetTotalSignature(3989776673u);

			AgentMeta* meta = NULL;
			BEHAVIAC_UNUSED_VAR(meta);

			// behaviac::Agent
			meta = BEHAVIAC_NEW AgentMeta(24743406u);
			AgentMeta::GetAgentMetas()[1770892321u] = meta;
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_behaviac_Agent_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd());
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear());
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains());
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength());
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove());

			// blackboard
			meta = BEHAVIAC_NEW AgentMeta(463107915u);
			AgentMeta::GetAgentMetas()[2686683804u] = meta;
			meta->RegisterMemberProperty(1892789304u, BEHAVIAC_NEW CMemberProperty< bool >("ManualCommand", Set_blackboard_ManualCommand, Get_blackboard_ManualCommand));
			meta->RegisterMemberProperty(1629854763u, BEHAVIAC_NEW CMemberProperty< bool >("NewTarget", Set_blackboard_NewTarget, Get_blackboard_NewTarget));
			meta->RegisterMemberProperty(683211792u, BEHAVIAC_NEW CMemberProperty< int >("TargetsFound", Set_blackboard_TargetsFound, Get_blackboard_TargetsFound));
			meta->RegisterMemberProperty(1778792245u, BEHAVIAC_NEW CMemberProperty< int >("TotalTargets", Set_blackboard_TotalTargets, Get_blackboard_TotalTargets));
			meta->RegisterMethod(2866457923u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_blackboard_LogicInit));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_blackboard_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd());
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear());
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains());
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength());
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove());

			// Process
			meta = BEHAVIAC_NEW AgentMeta(2162825115u);
			AgentMeta::GetAgentMetas()[1392889070u] = meta;
			meta->RegisterMemberProperty(951277069u, BEHAVIAC_NEW CMemberProperty< bool >("Finnished", Set_Process_Finnished, Get_Process_Finnished));
			meta->RegisterMemberProperty(3170843310u, BEHAVIAC_NEW CMemberProperty< bool >("Init", Set_Process_Init, Get_Process_Init));
			meta->RegisterMemberProperty(1573563529u, BEHAVIAC_NEW CMemberProperty< bool >("Replan", Set_Process_Replan, Get_Process_Replan));
			meta->RegisterMemberProperty(4017320758u, BEHAVIAC_NEW CMemberProperty< behaviac::vector<int> >("VehicleID", Set_Process_VehicleID, Get_Process_VehicleID));
			meta->RegisterMemberProperty(3085917903u, BEHAVIAC_NEW CMemberArrayItemProperty< int >("VehicleID[]", Set_Process_VehicleID, Get_Process_VehicleID));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_Process_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd());
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear());
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains());
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength());
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove());
			meta->RegisterMethod(1861935329u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_Process_VehicleVectorEmpty));

			// Coverage
			meta = BEHAVIAC_NEW AgentMeta(194611947u);
			AgentMeta::GetAgentMetas()[2078471360u] = meta;
			meta->RegisterMemberProperty(951277069u, BEHAVIAC_NEW CMemberProperty< bool >("Finnished", Set_Process_Finnished, Get_Process_Finnished));
			meta->RegisterMemberProperty(3170843310u, BEHAVIAC_NEW CMemberProperty< bool >("Init", Set_Process_Init, Get_Process_Init));
			meta->RegisterMemberProperty(1573563529u, BEHAVIAC_NEW CMemberProperty< bool >("Replan", Set_Process_Replan, Get_Process_Replan));
			meta->RegisterMemberProperty(4017320758u, BEHAVIAC_NEW CMemberProperty< behaviac::vector<int> >("VehicleID", Set_Process_VehicleID, Get_Process_VehicleID));
			meta->RegisterMemberProperty(3085917903u, BEHAVIAC_NEW CMemberArrayItemProperty< int >("VehicleID[]", Set_Process_VehicleID, Get_Process_VehicleID));
			meta->RegisterMethod(3631267655u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Coverage_DevideArea));
			meta->RegisterMethod(3848442565u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Coverage_FindCoveragePath));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_Coverage_LogMessage));
			meta->RegisterMethod(1406269780u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Coverage_SetGroup));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd());
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear());
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains());
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength());
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove());
			meta->RegisterMethod(1861935329u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_Coverage_VehicleVectorEmpty));

			// Revisit
			meta = BEHAVIAC_NEW AgentMeta(2037897485u);
			AgentMeta::GetAgentMetas()[4138899971u] = meta;
			meta->RegisterMemberProperty(951277069u, BEHAVIAC_NEW CMemberProperty< bool >("Finnished", Set_Process_Finnished, Get_Process_Finnished));
			meta->RegisterMemberProperty(2515708436u, BEHAVIAC_NEW CMemberProperty< bool >("IgnoreBlindSpot", Set_Revisit_IgnoreBlindSpot, Get_Revisit_IgnoreBlindSpot));
			meta->RegisterMemberProperty(3170843310u, BEHAVIAC_NEW CMemberProperty< bool >("Init", Set_Process_Init, Get_Process_Init));
			meta->RegisterMemberProperty(1573563529u, BEHAVIAC_NEW CMemberProperty< bool >("Replan", Set_Process_Replan, Get_Process_Replan));
			meta->RegisterMemberProperty(4017320758u, BEHAVIAC_NEW CMemberProperty< behaviac::vector<int> >("VehicleID", Set_Process_VehicleID, Get_Process_VehicleID));
			meta->RegisterMemberProperty(3085917903u, BEHAVIAC_NEW CMemberArrayItemProperty< int >("VehicleID[]", Set_Process_VehicleID, Get_Process_VehicleID));
			meta->RegisterMethod(2379079005u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Revisit_AskForBlindSpot));
			meta->RegisterMethod(1769076042u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Revisit_FindRevisitOrder));
			meta->RegisterMethod(1343724573u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Revisit_FindRevisitPath));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_Revisit_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd());
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear());
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains());
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength());
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove());
			meta->RegisterMethod(1861935329u, BEHAVIAC_NEW CAgentMethod< bool >(FunctionPointer_Revisit_VehicleVectorEmpty));

			// Recognize
			meta = BEHAVIAC_NEW AgentMeta(1980793486u);
			AgentMeta::GetAgentMetas()[3642170052u] = meta;
			meta->RegisterMemberProperty(520410890u, BEHAVIAC_NEW CMemberProperty< bool >("AmmunitionAvaiable", Set_Recognize_AmmunitionAvaiable, Get_Recognize_AmmunitionAvaiable));
			meta->RegisterMemberProperty(2367019555u, BEHAVIAC_NEW CMemberProperty< bool >("CanBeRecognized", Set_Recognize_CanBeRecognized, Get_Recognize_CanBeRecognized));
			meta->RegisterMemberProperty(743577581u, BEHAVIAC_NEW CMemberProperty< bool >("NeedEliminated", Set_Recognize_NeedEliminated, Get_Recognize_NeedEliminated));
			meta->RegisterMethod(1039053482u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Recognize_AddToEliminate));
			meta->RegisterMethod(2471577796u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Recognize_AddToRevisit));
			meta->RegisterMethod(2280178816u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Recognize_ApproachAndRecognize));
			meta->RegisterMethod(1136222074u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Recognize_Eliminate));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_Recognize_LogMessage));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd());
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear());
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains());
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength());
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove());

			// Interact
			meta = BEHAVIAC_NEW AgentMeta(2765218838u);
			AgentMeta::GetAgentMetas()[3777618981u] = meta;
			meta->RegisterMemberProperty(222163095u, BEHAVIAC_NEW CMemberProperty< TaskType >("InteractTask", Set_Interact_InteractTask, Get_Interact_InteractTask));
			meta->RegisterMethod(1045109914u, BEHAVIAC_NEW CAgentStaticMethodVoid_1<char*>(FunctionPointer_Interact_LogMessage));
			meta->RegisterMethod(2754924504u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Interact_MoveTo));
			meta->RegisterMethod(3717590755u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Interact_Resume));
			meta->RegisterMethod(332667174u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Interact_SetTargetType));
			meta->RegisterMethod(4162527135u, BEHAVIAC_NEW CAgentMethodVoid(FunctionPointer_Interact_TurnBack));
			meta->RegisterMethod(2521019022u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorAdd());
			meta->RegisterMethod(2306090221u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorClear());
			meta->RegisterMethod(3483755530u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorContains());
			meta->RegisterMethod(505785840u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorLength());
			meta->RegisterMethod(502968959u, BEHAVIAC_NEW CMethod_behaviac_Agent_VectorRemove());

			AgentMeta::Register<behaviac::Agent>("behaviac::Agent");
			AgentMeta::Register<blackboard>("blackboard");
			AgentMeta::Register<Process>("Process");
			AgentMeta::Register<Coverage>("Coverage");
			AgentMeta::Register<Revisit>("Revisit");
			AgentMeta::Register<Recognize>("Recognize");
			AgentMeta::Register<Interact>("Interact");
			AgentMeta::Register<TaskType>("TaskType");

			Agent::RegisterInstanceName<blackboard>("blackboard");
			Agent::RegisterInstanceName<behaviac::Agent>("behaviac::Agent");
			Agent::RegisterInstanceName<Coverage>("Coverage");
			Agent::RegisterInstanceName<Revisit>("Revisit");
			Agent::RegisterInstanceName<Recognize>("Recognize");
			Agent::RegisterInstanceName<Interact>("Interact");

			return true;
		}

		virtual bool unLoad()
		{
			AgentMeta::UnRegister<behaviac::Agent>("behaviac::Agent");
			AgentMeta::UnRegister<blackboard>("blackboard");
			AgentMeta::UnRegister<Process>("Process");
			AgentMeta::UnRegister<Coverage>("Coverage");
			AgentMeta::UnRegister<Revisit>("Revisit");
			AgentMeta::UnRegister<Recognize>("Recognize");
			AgentMeta::UnRegister<Interact>("Interact");
			AgentMeta::UnRegister<TaskType>("TaskType");

			Agent::UnRegisterInstanceName<blackboard>("blackboard");
			Agent::UnRegisterInstanceName<behaviac::Agent>("behaviac::Agent");
			Agent::UnRegisterInstanceName<Coverage>("Coverage");
			Agent::UnRegisterInstanceName<Revisit>("Revisit");
			Agent::UnRegisterInstanceName<Recognize>("Recognize");
			Agent::UnRegisterInstanceName<Interact>("Interact");

			return true;
		}
	};

	static BehaviorLoaderImplement _behaviorLoaderImplement_;

	static BehaviorLoaderImplement* _pBehaviorLoader_ = NULL;

	void InitBehaviorLoader()
	{
		_pBehaviorLoader_ = BEHAVIAC_NEW BehaviorLoaderImplement();
	}

	void DestroyBehaviorLoader()
	{
		if (_pBehaviorLoader_)
		{
			BEHAVIAC_DELETE _pBehaviorLoader_;
			_pBehaviorLoader_ = NULL;
		}
	}
}
