// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers



struct METHOD_TYPE_Process_VehicleVectorEmpty { };
template<> inline bool Process::_Execute_Method_<METHOD_TYPE_Process_VehicleVectorEmpty>()
{
	return this->Process::VehicleVectorEmpty();
}


struct METHOD_TYPE_Coverage_SetGroup { };
template<> inline void Coverage::_Execute_Method_<METHOD_TYPE_Coverage_SetGroup>()
{
	this->Coverage::SetGroup();
}




struct METHOD_TYPE_Interact_MoveTo { };
template<> inline void Interact::_Execute_Method_<METHOD_TYPE_Interact_MoveTo>()
{
	this->Interact::MoveTo();
}

struct METHOD_TYPE_Interact_TurnBack { };
template<> inline void Interact::_Execute_Method_<METHOD_TYPE_Interact_TurnBack>()
{
	this->Interact::TurnBack();
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
