// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_AGENT_HEADERS_H_
#define _BEHAVIAC_AGENT_HEADERS_H_

#include "behaviac_headers.h"

// THE FOLLOWING AGENT HEADER FILES IS GENERATED AUTOMATICALLY:
#include "blackboard.h"
#include "Process.h"
#include "Coverage.h"
#include "Revisit.h"
#include "Recognize.h"
#include "Interact.h"

#endif // _BEHAVIAC_AGENT_HEADERS_H_
