// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_COVERAGE_H_
#define _BEHAVIAC_COVERAGE_H_

#include "behaviac_headers.h"

#include "Process.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include  "blackboard.h"

class blackboard;
extern blackboard* g_BlackBoardAgent;
///<<< END WRITING YOUR CODE

class Coverage : public Process
///<<< BEGIN WRITING YOUR CODE Coverage
///<<< END WRITING YOUR CODE
{
public:
	Coverage();
	virtual ~Coverage();

	BEHAVIAC_DECLARE_AGENTTYPE(Coverage, Process)

	public: void DevideArea();

	public: void FindCoveragePath();

	private: void SetGroup();

///<<< BEGIN WRITING YOUR CODE CLASS_PART
	public:std::vector<std::pair<int,int>> group_msg;
	
	public:std::vector<std::vector<cv::Point>>  divided_areas;

	public:std::vector<std::vector<cv::Point2f>> CoveragePath;
///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE


#endif
