// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_INTERACT_H_
#define _BEHAVIAC_INTERACT_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE
#include "Coverage.h"
#include "Revisit.h"
#include "Recognize.h"
extern Coverage* g_CoverageAgent;
extern Revisit* g_RevisitAgent;
extern Recognize* g_RecognizeAgent;
extern blackboard* g_BlackBoardAgent;

class Interact : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE Interact
///<<< END WRITING YOUR CODE
{
public:
	Interact();
	virtual ~Interact();

	BEHAVIAC_DECLARE_AGENTTYPE(Interact, behaviac::Agent)

	public: TaskType InteractTask;

	private: void MoveTo();

	public: void Resume();

	public: void SetTargetType();

	private: void TurnBack();

	//add
	public:
		std::vector<int> EnableIndexes;
		std::vector<int> DisableIndexes;
		int MoveVehicleIndex;
		LatLngPoint MoveToPt;
		int TargetType;
		int TargetLoc;
		int ManualIndex;
		std::vector<std::vector<cv::Point2f>> manual_traj;
///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
