// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_PROCESS_H_
#define _BEHAVIAC_PROCESS_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

class Process : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE Process
///<<< END WRITING YOUR CODE
{
public:
	Process();
	virtual ~Process();

	BEHAVIAC_DECLARE_AGENTTYPE(Process, behaviac::Agent)

	public: bool Finnished;

	public: bool Init;

	public: bool Replan;

	public: behaviac::vector<int> VehicleID;

	public: bool VehicleVectorEmpty();

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
