// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_RECOGNIZE_H_
#define _BEHAVIAC_RECOGNIZE_H_

#include "behaviac_headers.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
#include "Revisit.h"
#include "blackboard.h"

extern Revisit* g_RevisitAgent;
extern blackboard* g_BlackBoardAgent;
///<<< END WRITING YOUR CODE

class Recognize : public behaviac::Agent
///<<< BEGIN WRITING YOUR CODE Recognize
///<<< END WRITING YOUR CODE
{
public:
	Recognize();
	virtual ~Recognize();

	BEHAVIAC_DECLARE_AGENTTYPE(Recognize, behaviac::Agent)

	public: bool AmmunitionAvaiable;

	public: bool CanBeRecognized;

	public: bool NeedEliminated;

	public: void AddToEliminate();

	public: void AddToRevisit();

	public: void AddRevisitForNewScene();

	public: void ApproachAndRecognize();

	public: void Eliminate();

	public: void Eliminate_NewScene();

	public: void DoRevisitAct();	// 执行重访动作

	public: void DoRevisitAct_NewScene();	// 新场景下执行重访动作
	//抵近观察位置或确定目标位置
	LatLngPoint target_location;
	int car_index;

	std::vector<clock_t> eliminate_start_time;

	std::vector<clock_t> eliminate_start_time_new_scene;
	
	int Eliminate_MineIndex;
	int Eliminate_CarIndex;


///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
