// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

#ifndef _BEHAVIAC_REVISIT_H_
#define _BEHAVIAC_REVISIT_H_

#include "behaviac_headers.h"
#include "Process.h"
#include "blackboard.h"

///<<< BEGIN WRITING YOUR CODE FILE_INIT
class blackboard;
extern blackboard* g_BlackBoardAgent;
extern Transfer transfer_;
///<<< END WRITING YOUR CODE

class Revisit : public Process
///<<< BEGIN WRITING YOUR CODE Revisit
///<<< END WRITING YOUR CODE
{
public:
	Revisit();
	virtual ~Revisit();

	BEHAVIAC_DECLARE_AGENTTYPE(Revisit, Process)

	public: bool IgnoreBlindSpot;

	public: void AskForBlindSpot();

	public: void FindRevisitOrder();

	public: void FindRevisitPath();

	public: void FindRevisitPath_NewScene();

///<<< BEGIN WRITING YOUR CODE CLASS_PART
	public:std::vector<std::vector<cv::Point>> revisit_trajs;

	public: std::vector<cv::Point> mine_pos;

	public: std::vector<cv::Point> mine_pos_new_scene;

	public: int car_num;

	public: LatLngPoint vehicle_start_pt; // 仿真用到的起始点
///<<< END WRITING YOUR CODE
};

class Solution {
public:
	Solution(std::vector<Point> mines_, int weapon_num_, bool one_channel_, std::vector<Point> area_) :mines(mines_), weapon_num(weapon_num_), area(area_), one_channel(one_channel_) {};
	std::vector<int> find_channel_pos();
	std::vector<Point> mines;
	std::vector<Point> area;
	int weapon_num;
	std::vector<int> priority;
	bool one_channel;
};

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

#endif
